name: "Linting"
description: "Run linters"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-uv
      with:
        PYTHON_VERSION: "3.10"

    - name: Ruff check and format
      shell: bash
      run: |
        uv run --only-dev ruff check
        uv run --only-dev ruff format --check