[build-system]
requires = ["setuptools"]

[project]
name = "evo-data-converters"
requires-python = ">=3.10"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE.md", content-type = "text/markdown" }
version = "0.0.3"
dependencies = [
  "aiohttp",
  "evo-client-common==0.1.0",
  "evo-objects==0.1.0",
  "nest-asyncio",
  "numpy<2.0.0",
  "omf>=1.0.1",
  "omf2>=0.1.0-beta.1",
  "pandas==2.2.3",
  "pyarrow",
  "pure-interface",
  "resqpy==5.1.10",
  "seequent-geoscience-object-schemas>=2024.6",
  "scipy",
  "vtk",
]

[dependency-groups]
dev = [
  "build",
  "mypy",
  "pre-commit",
  "pytest>=8.2",
  "pytest-asyncio",
  "ruff",
  "requests-mock"
]

# Optional dependencies for running notebooks
notebooks = ["jupyter"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
  ".git",
  ".git-rewrite",
  ".mypy_cache",
  ".pytype",
  ".ruff_cache",
  ".venv",
  "__pypackages__",
  "_build",
  "build",
  "dist",
  "venv",
]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP006"]

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
# Exclude this directory because the python scripts require extra dependencies to be installed.
exclude = ["samples/geoscience-objects/python/helpers"]
ignore_missing_imports = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

# Use Artifactory for now as the ssh keys seem like even more admin.
# [tool.uv.sources]
# evo-object-client = { git = "https://git@github.com/seequent/evo-object-client" }
# evo-client-common = { git = "https://git@github.com/seequent/evo-client-common" }
# seequent-geoscience-object-schemas = { git = "https://git@github.com/seequent/geoscience-object-schemas" }
