#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""Version detection and normalisation of pre-1.0 AGSi documents to the 1.0.x layout.

AGSi v0.6 (used by early published examples) differs from 1.0.x mainly in what it omits:
there is no ``agsSchema``, ``agsFile`` or ``agsProject`` object, and the version is only
recorded in the package ``index.json``. Some pre-release files also used ``agsi``-prefixed
names for the general objects. The adapter fills these gaps in memory without changing the
model content.
"""

import copy
from typing import Any, Optional

CURRENT_VERSION = "1.0.1"
LEGACY_DEFAULT_VERSION = "0.6"
ADAPTER_REMARK = "Generated by evo-data-converters-agsi when normalising an AGSi {version} document to {target}."

_RENAMED_ROOT_KEYS = {
    "agsiSchema": "agsSchema",
    "agsiFile": "agsFile",
    "agsiProject": "agsProject",
}
_RENAMED_PROJECT_KEYS = {
    "agsiProjectCoordinateSystem": "agsProjectCoordinateSystem",
    "agsiProjectInvestigation": "agsProjectInvestigation",
    "agsiProjectDocumentSet": "agsProjectDocumentSet",
    "agsiProjectCodeSet": "agsProjectCodeSet",
}


def major_version(version: str) -> Optional[int]:
    head = str(version).strip().lstrip("vV").split(".")[0]
    return int(head) if head.isdigit() else None


def is_legacy_version(version: str) -> bool:
    """True for pre-1.0 versions (e.g. ``"0.6"``)."""
    return major_version(version) == 0


def detect_version(document: dict[str, Any], index_version: Optional[str] = None) -> str:
    """Determine the AGSi version of a parsed main JSON document.

    Precedence: ``agsSchema.version`` in the document, then ``fileVersion`` from the package
    ``index.json``. Documents with neither are assumed to be pre-1.0 (``agsSchema`` is
    required from 1.0 onwards).
    """
    for key in ("agsSchema", "agsiSchema"):
        schema = document.get(key)
        if isinstance(schema, dict) and schema.get("version"):
            return str(schema["version"])
    if index_version:
        return str(index_version)
    return LEGACY_DEFAULT_VERSION


def normalise_document(
    document: dict[str, Any],
    version: str,
    *,
    title: Optional[str] = None,
    file_name: Optional[str] = None,
) -> tuple[dict[str, Any], list[str]]:
    """Return a copy of ``document`` in AGSi 1.0.x layout, plus notes describing any changes.

    1.x documents are returned unchanged. For pre-1.0 documents the adapter:

    * renames ``agsi``-prefixed general objects (``agsiFile`` -> ``agsFile`` etc.);
    * wraps a single ``agsiModel`` / ``agsiModelElement`` object in a list;
    * moves a ``geometryObject`` nested inside ``agsiGeometry`` up to the model element;
    * synthesises the required ``agsSchema``, ``agsFile`` and ``agsProject`` objects.

    :param title: Title for synthesised ``agsFile``/``agsProject`` (e.g. ``index.json`` name).
    :param file_name: Name of the main JSON file, recorded as ``agsFile.fileURI``.
    """
    result = copy.deepcopy(document)
    notes: list[str] = []
    if not is_legacy_version(version):
        major = major_version(version)
        if major is not None and major > 1:
            notes.append(f"AGSi version {version} is newer than {CURRENT_VERSION}; reading it as {CURRENT_VERSION}.")
        return result, notes

    for old, new in _RENAMED_ROOT_KEYS.items():
        if old in result and new not in result:
            result[new] = result.pop(old)
            notes.append(f"Renamed '{old}' to '{new}'.")
    project = result.get("agsProject")
    if isinstance(project, dict):
        for old, new in _RENAMED_PROJECT_KEYS.items():
            if old in project and new not in project:
                project[new] = project.pop(old)
                notes.append(f"Renamed 'agsProject.{old}' to '{new}'.")

    models = result.get("agsiModel")
    if isinstance(models, dict):
        result["agsiModel"] = models = [models]
        notes.append("Wrapped single 'agsiModel' object in a list.")
    for model in models if isinstance(models, list) else []:
        if not isinstance(model, dict):
            continue
        elements = model.get("agsiModelElement")
        if isinstance(elements, dict):
            model["agsiModelElement"] = elements = [elements]
            notes.append("Wrapped single 'agsiModelElement' object in a list.")
        for element in elements if isinstance(elements, list) else []:
            geometry = element.get("agsiGeometry") if isinstance(element, dict) else None
            if isinstance(geometry, dict) and "geometryObject" in geometry:
                nested = geometry.pop("geometryObject")
                element.setdefault("geometryObject", nested)
                notes.append(f"Moved 'geometryObject' out of 'agsiGeometry' for element '{element.get('elementID')}'.")

    first_model = models[0] if isinstance(models, list) and models and isinstance(models[0], dict) else {}
    name = title or first_model.get("modelName") or file_name or "Untitled AGSi model"
    remark = ADAPTER_REMARK.format(version=version, target=CURRENT_VERSION)

    schema = result.get("agsSchema")
    original_schema: dict[str, Any] = schema if isinstance(schema, dict) else {}
    result["agsSchema"] = {**original_schema, "name": "AGSi", "version": CURRENT_VERSION}
    notes.append(f"Set 'agsSchema' version {CURRENT_VERSION} (source version {version}).")

    if not isinstance(result.get("agsFile"), dict):
        ags_file: dict[str, Any] = {"title": name, "producedBy": "Unknown", "remarks": remark}
        if file_name:
            ags_file["fileURI"] = file_name
        result["agsFile"] = ags_file
        notes.append("Synthesised missing 'agsFile'.")

    if not isinstance(result.get("agsProject"), dict):
        result["agsProject"] = {"projectName": name, "remarks": remark}
        notes.append("Synthesised missing 'agsProject' (no coordinate system defined).")

    # Keep the conventional key order: general objects first, then models.
    ordered: dict[str, Any] = {k: result.pop(k) for k in ("agsSchema", "agsFile", "agsProject") if k in result}
    ordered.update(result)
    return ordered, notes
