from evo.data_converters.duf.importer import convert_duf


async def convert_duf_to_evo(selected_file_path: str, epsg_code: int, upload_path: str, manager):
    """
    Convert the provided DUF file and publish objects to Evo.

    Args:
        selected_file_path: Full path to the .duf file.
        epsg_code: EPSG integer code for CRS.
        upload_path: Optional Evo object path ("" for root).
        manager: Authenticated Evo manager providing credentials.

    Returns:
        The published object metadata.
    """

    tags = {"Source": "Auto-generated by DUF converter notebook"}

    objects_metadata = await convert_duf(
        filepath=selected_file_path,
        epsg_code=epsg_code,
        service_manager_widget=manager,
        tags=tags,
        upload_path=upload_path,
        combine_objects_in_layers=True,
        overwrite_existing_objects=True,
    )

    # Return single combined object
    return objects_metadata if objects_metadata else None
