#  Copyright © 2025 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


import argparse
import pprint
import sys
from pathlib import Path

from evo.data_converters.common.evo_client import EvoWorkspaceMetadata
from evo.data_converters.duf import DUFFileNotFoundException, InvalidDUFFileException
from evo.data_converters.duf.importer import convert_duf


def main():
    """Main function to handle command line execution."""
    parser = argparse.ArgumentParser(description="Convert DUF files and publish to EVO workspace")
    parser.add_argument("--duf-file", "-f", required=True, help="Path to the DUF file to convert")
    parser.add_argument("--org-id", required=True, help="Evo organization ID")
    parser.add_argument("--workspace-id", required=True, help="Evo workspace ID")
    parser.add_argument("--client-id", required=True, help="Evo client ID")
    parser.add_argument("--client-secret", required=True, help="Evo client secret")
    parser.add_argument("--hub-url", required=True, help="Evo hub URL")
    parser.add_argument("--user-agent", required=True, help="User agent string")
    parser.add_argument("--epsg-code", type=int, required=True, help="EPSG code for coordinate reference system")
    parser.add_argument("--upload-path", default="", help="Upload path in the workspace (default: root level)")
    parser.add_argument("--combine-layers", action="store_true", default=True, help="Combine objects in layers")

    args = parser.parse_args()

    # Validate DUF file exists
    duf_file = Path(args.duf_file)
    if not duf_file.exists():
        print(f"Error: DUF file not found: {duf_file}")
        sys.exit(1)

    # Create Evo workspace credentials
    creds = EvoWorkspaceMetadata(
        org_id=args.org_id,
        workspace_id=args.workspace_id,
        client_id=args.client_id,
        client_secret=args.client_secret,
        hub_url=args.hub_url,
        user_id=args.user_agent,
    )

    print(f"Converting DUF file: {duf_file}")
    print(f"EPSG Code: {args.epsg_code}")
    print(f"Upload Path: {args.upload_path if args.upload_path else '(root level)'}")
    print(f"Combine Layers: {args.combine_layers}")
    print("-" * 50)

    # Set up tags
    tags = {"Source": "Auto-generated by DUF converter script"}

    try:
        # Call convert_duf function
        objects_metadata = convert_duf(
            filepath=str(duf_file),
            epsg_code=args.epsg_code,
            evo_workspace_metadata=creds,
            tags=tags,
            upload_path=args.upload_path,
            combine_objects_in_layers=args.combine_layers,
            overwrite_existing_objects=True,
        )

        print()
        print("These objects have now been published:")
        print("-" * 50)

        for metadata in objects_metadata:
            pprint.pp(metadata, indent=4)

        print(f"\nSuccessfully converted and published {len(objects_metadata)} objects!")

    except DUFFileNotFoundException as e:
        print("Error: DUF file not found")
        print(f"Details: {str(e)}")
        sys.exit(1)
    except InvalidDUFFileException as e:
        print("Error: Invalid DUF file format")
        print(f"Details: {str(e)}")
        print("Please ensure the file is a valid Deswik Unified File (DUF)")
        sys.exit(1)
    except ValueError as e:
        print("Error: Invalid parameter value")
        print(f"Details: {str(e)}")
        sys.exit(1)
    except ConnectionError as e:
        print("Error: Failed to connect to Evo workspace")
        print(f"Details: {str(e)}")
        print("Please check your network connection and Evo credentials")
        sys.exit(1)
    except Exception as e:
        print("Error: An unexpected error occurred during conversion")
        print(f"Details: {str(e)}")
        print(f"Error type: {type(e).__name__}")
        sys.exit(1)


if __name__ == "__main__":
    main()
