class IPJ_ORIENT_TYPE:
    IPJ_ORIENT_DEFAULT = 0
    IPJ_ORIENT_PLAN = 1
    IPJ_ORIENT_SECTION = 2
    IPJ_ORIENT_DEPTH_SECTION = 3
    IPJ_ORIENT_3D = 4
    IPJ_ORIENT_SECTION_NORMAL = 5
    IPJ_ORIENT_SECTION_CROOKED = 6
    IPJ_ORIENT_3D_MATRIX = 7
