from collections import defaultdict

import evo.data_converters.duf.common.deswik_types as dw
from evo.data_converters.common import (
    create_evo_object_service_and_data_client,
    crs_from_any,
    publish_geoscience_objects,
)
from evo.data_converters.duf.duf_reader_context import DUFCollectorContext
from evo.data_converters.duf.importer import convert_duf
from evo.data_converters.duf.importer.duf_to_evo import (
    COMBINING_CONVERTERS,
    _get_converter,
    _validate_entity,
)
from evo.data_converters.duf.importer.utils import ConvertOptions, ResolveObjectNameOption


async def convert_duf_to_evo(selected_file_path: str, epsg_code: int, upload_path: str, manager):
    """
    Convert the provided DUF file and publish objects to Evo.

    Args:
        selected_file_path: Full path to the .duf file.
        epsg_code: EPSG integer code for CRS.
        upload_path: Optional Evo object path ("" for root).
        manager: Authenticated Evo manager providing credentials.

    Returns:
        The published object metadata.
    """

    tags = {"Source": "Auto-generated by DUF converter notebook"}

    objects_metadata = await convert_duf(
        filepath=selected_file_path,
        coordinate_reference_system=epsg_code,
        service_manager_widget=manager,
        tags=tags,
        upload_path=upload_path,
        combine_objects_in_layers=True,
        overwrite_existing_objects=True,
        resolve_object_name=ResolveObjectNameOption.CONCATENATE,
    )

    # Return single combined object
    return objects_metadata


def read_duf_layers(filepath):
    """Read a DUF file and return layer information.

    Args:
        filepath: Full path to the .duf file.

    Returns:
        Tuple of (layer_info, collector) where layer_info is a list of dicts
        with 'name' keys, and collector is the ObjectCollector
        for use in subsequent conversion.
    """

    with DUFCollectorContext(filepath) as context:
        collector = context.collector

    by_layer = collector.get_objects_with_category_by_layer(dw.Category.ModelEntities)

    layer_info = []
    for layer, objs in by_layer.items():
        name = layer.Name if layer else "<No Layer>"
        layer_info.append(
            {
                "name": name,
                "count": len(objs),
            }
        )

    return layer_info, collector


def convert_selected_layers_to_evo(collector, selected_layer_names, epsg_code, manager):
    """Convert only objects from selected layers into geoscience objects.

    Args:
        collector: ObjectCollector from read_duf_layers.
        selected_layer_names: List of layer names to convert.
        epsg_code: EPSG integer code for CRS.
        manager: Authenticated Evo manager providing credentials.

    Returns:
        List of converted geoscience objects (not yet published).
    """

    _, data_client = create_evo_object_service_and_data_client(
        service_manager_widget=manager,
    )

    crs = crs_from_any(epsg_code)
    tags = {"Source": "Auto-generated by DUF converter notebook", "Category": "ModelEntities"}

    options = ConvertOptions(
        combined=True,
        resolve_object_name=ResolveObjectNameOption.CONCATENATE,
    )

    by_layer = collector.get_objects_with_category_by_layer(dw.Category.ModelEntities)
    selected_names = set(selected_layer_names)

    geoscience_objects = []
    for layer, objs in by_layer.items():
        layer_name = layer.Name if layer else "<No Layer>"
        if layer_name not in selected_names:
            continue

        layer_by_type = defaultdict(list)
        for obj in objs:
            layer_by_type[type(obj)].append(obj)

        objs_to_convert_as_group = {}
        for klass, layer_type_objs in layer_by_type.items():
            converter = _get_converter(klass, COMBINING_CONVERTERS, warn=False)
            if converter is None:
                continue
            valid_objs = [obj for obj in layer_type_objs if _validate_entity(obj)]
            objs_so_far = objs_to_convert_as_group.setdefault(converter, [])
            objs_so_far.extend(valid_objs)

        for layer_converter, objs_to_convert in objs_to_convert_as_group.items():
            if len(objs_to_convert) == 0:
                continue
            geoscience_object = layer_converter(objs_to_convert, data_client, crs, options)
            if geoscience_object:
                if geoscience_object.tags is None:
                    geoscience_object.tags = {}
                geoscience_object.tags.update(tags)
                geoscience_objects.append(geoscience_object)

    return geoscience_objects


async def publish_selected_objects(selected_objects, upload_path: str, manager):
    """
    Publish a list of selected geoscience objects to Evo.

    Args:
        selected_objects: List of geoscience objects to publish.
        upload_path: Optional Evo object path ("" for root).
        manager: Authenticated Evo manager providing credentials.

    Returns:
        List of published object metadata.
    """
    object_service_client, data_client = create_evo_object_service_and_data_client(
        service_manager_widget=manager,
    )

    objects_metadata = await publish_geoscience_objects(
        selected_objects, object_service_client, data_client, upload_path, overwrite_existing_objects=True
    )

    return objects_metadata
