import evo.data_converters.duf.common.deswik_types as dw
from evo.data_converters.duf.duf_reader_context import DUFCollectorContext
from evo.data_converters.duf.importer import convert_duf
from evo.data_converters.duf.importer.utils import ResolveObjectNameOption


async def convert_duf_to_evo(filepath: str, epsg_code: int, upload_path: str, manager, layers: list[str] | None = None):
    """
    Convert the provided DUF file and publish objects to Evo.

    Args:
        filepath: Full path to the .duf file.
        epsg_code: EPSG integer code for CRS.
        upload_path: Optional Evo object path ("" for root).
        manager: Authenticated Evo manager providing credentials.
        layers: Optional list of layer names to include. If None, all layers are converted.

    Returns:
        The published object metadata.
    """

    tags = {"Source": "Auto-generated by DUF converter notebook"}

    objects_metadata = await convert_duf(
        filepath=filepath,
        epsg_code=epsg_code,
        service_manager_widget=manager,
        tags=tags,
        upload_path=upload_path,
        combine_objects_in_layers=True,
        overwrite_existing_objects=True,
        resolve_object_name=ResolveObjectNameOption.CONCATENATE,
        layers=set(layers) if layers else None,
    )

    return objects_metadata


def read_duf_layers(filepath):
    """Read a DUF file and return layer information.

    Args:
        filepath: Full path to the .duf file.

    Returns:
        List of dicts with 'name' and 'count' keys describing each layer.
    """

    with DUFCollectorContext(filepath) as context:
        collector = context.collector

    by_layer = collector.get_objects_with_category_by_layer(dw.Category.ModelEntities)

    layer_info = []
    for layer, objs in by_layer.items():
        if layer is None:
            continue
        layer_info.append({"name": layer.Name, "count": len(objs)})

    return layer_info
