name: Build and publish package

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        python-version: [ "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testing
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}

  build-package:
    name: Build package
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-uv
        with:
          PYTHON_VERSION: "3.10"

      - name: Build
        shell: bash
        run: uv build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

      - name: Publish package
        shell: bash
        run: |
          "Coming soon..."
