on:
  release:
    types: [released]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-and-publish:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      # Required for publishing release artifacts
      contents: write
      # Required for PyPI trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-uv
        with:
          PYTHON_VERSION: "3.10"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build wheel (to dist folder)
        run: uv build

      - name: Publish package distributions to PyPI (from dist folder)
        uses: pypa/gh-action-pypi-publish@release/v1
