name: Build and publish evo-data-converters-duf

permissions:
  # Required for publishing release artifacts
  contents: write
  # Required for PyPI trusted publishing
  id-token: write

on:
  release:
    types: [released]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-uv

      - name: Build package
        shell: bash
        run: uv build --package evo-data-converters-duf

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Upload artifact to GitHub Release
        shell: bash
        run: gh release upload ${{ github.event.release.tag_name }} dist/*
