#  Copyright © 2025 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


import argparse
import asyncio
import os
import pprint
import sys
from pathlib import Path

from evo.data_converters.common.evo_client import EvoWorkspaceMetadata
from evo.data_converters.duf.importer import convert_duf


def main():
    """Main function to handle command line execution."""
    parser = argparse.ArgumentParser(
        description="Convert DUF files and publish to Evo workspace",
        epilog=(
            "Combine behavior uses paired flags: --combine-layers / --no-combine-layers. "
            "If both are provided, argparse applies the last one on the command line."
        ),
    )
    parser.add_argument("--duf-file", "-f", required=True, help="Path to the DUF file to convert")
    parser.add_argument("--org-id", required=True, help="Evo organization ID")
    parser.add_argument("--workspace-id", required=True, help="Evo workspace ID")
    parser.add_argument("--client-id", required=True, help="Evo client ID")
    parser.add_argument(
        "--client-secret",
        required=False,
        help="Evo client secret (optional if EVO_CLIENT_SECRET environment variable is set)",
    )
    parser.add_argument("--hub-url", required=True, help="Evo hub URL")
    parser.add_argument("--user-agent", required=True, help="User agent string")
    parser.add_argument("--epsg-code", type=int, required=True, help="EPSG code for coordinate reference system")
    parser.add_argument("--upload-path", default="", help="Upload path in the workspace (default: root level)")
    parser.add_argument(
        "--combine-layers", dest="combine_layers", action="store_true", help="Combine objects in layers"
    )
    parser.add_argument(
        "--no-combine-layers",
        dest="combine_layers",
        action="store_false",
        help="Do not combine objects in layers",
    )
    parser.set_defaults(combine_layers=True)

    args = parser.parse_args()

    # Strip leading/trailing whitespace only.
    args.org_id = args.org_id.strip()
    args.workspace_id = args.workspace_id.strip()
    args.client_id = args.client_id.strip()
    args.client_secret = (
        args.client_secret if args.client_secret is not None else os.getenv("EVO_CLIENT_SECRET", "")
    ).strip()
    args.hub_url = args.hub_url.strip()
    args.user_agent = args.user_agent.strip()
    args.upload_path = args.upload_path.strip()

    if not args.client_secret:
        print("Error: missing client secret. Provide --client-secret or set EVO_CLIENT_SECRET.")
        sys.exit(1)

    # Validate DUF file exists
    duf_file = Path(args.duf_file)
    if not duf_file.exists() or not duf_file.is_file():
        print(f"Error: DUF file not found: {duf_file}")
        sys.exit(1)

    # Create Evo workspace credentials
    creds = EvoWorkspaceMetadata(
        org_id=args.org_id,
        workspace_id=args.workspace_id,
        client_id=args.client_id,
        client_secret=args.client_secret,
        hub_url=args.hub_url,
        user_id=args.user_agent,
    )

    print(f"Converting DUF file: {duf_file}")
    print(f"EPSG Code: {args.epsg_code}")
    print(f"Upload Path: {args.upload_path if args.upload_path else '(root level)'}")
    print(f"Combine Layers: {args.combine_layers}")
    print("-" * 50)

    # Set up tags
    tags = {"Source": "Auto-generated by DUF converter script"}

    # Call convert_duf function
    try:
        objects_metadata = asyncio.run(
            convert_duf(
                filepath=str(duf_file),
                epsg_code=args.epsg_code,
                evo_workspace_metadata=creds,
                tags=tags,
                upload_path=args.upload_path,
                combine_objects_in_layers=args.combine_layers,
                overwrite_existing_objects=True,
            )
        )
    except Exception as exc:
        print(f"Error during conversion/publish: {exc}")
        sys.exit(1)

    print()
    print("These objects have now been published:")
    print("-" * 50)

    for metadata in objects_metadata:
        pprint.pp(metadata, indent=4)

    print(f"\nSuccessfully converted and published {len(objects_metadata)} objects!")


if __name__ == "__main__":
    main()
